# Generated by Django 5.2.7 on 2025-10-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer_id', models.CharField(max_length=50)),
                ('event_name', models.CharField(max_length=100)),
                ('event_description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('schedule1_date', models.CharField(blank=True, max_length=100, null=True)),
                ('schedule1_date_time', models.CharField(blank=True, max_length=100, null=True)),
                ('schedule1_phase', models.CharField(blank=True, max_length=100, null=True)),
                ('schedule2_date', models.CharField(blank=True, max_length=100, null=True)),
                ('schedule2_date_time', models.CharField(blank=True, max_length=100, null=True)),
                ('schedule2_phase', models.CharField(blank=True, max_length=100, null=True)),
                ('organizer_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
