# Generated by Django 5.2.7 on 2025-10-10 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DispozenApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='event_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
