# Generated by Django 5.2.7 on 2025-10-10 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DispozenApp', '0002_eventmodel_event_category_alter_eventmodel_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
