# Generated by Django 5.2.7 on 2025-10-10 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DispozenApp', '0003_eventmodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodel',
            name='name',
        ),
    ]
