# Generated by Django 5.2.7 on 2025-10-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DispozenApp', '0004_remove_eventmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='event_description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
