# Generated by Django 5.2.7 on 2025-10-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DispozenApp', '0006_dispozenuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispozenuser',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='dispozenuser',
            name='fb_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
