# Generated by Django 5.2.7 on 2025-10-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DispozenApp', '0007_alter_dispozenuser_email_alter_dispozenuser_fb_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispozenuser',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='dispozenuser',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
