# Generated by Django 5.2.7 on 2025-10-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DispozenApp', '0008_remove_dispozenuser_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispozenuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dispozenuser',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='dispozenuser',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispozenuser',
            name='otp_used',
            field=models.BooleanField(default=False),
        ),
    ]
