# Generated by Django 5.2.7 on 2025-10-19 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DispozenApp', '0009_dispozenuser_is_verified_dispozenuser_otp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispozenuser',
            name='otp_used',
        ),
    ]
