# Generated by Django 5.2.7 on 2025-10-21 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DispozenApp', '0010_remove_dispozenuser_otp_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='organizer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
