# Generated by Django 5.2.7 on 2025-10-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DispozenApp', '0011_alter_eventmodel_organizer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='vote_maybe',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='vote_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='vote_yes',
            field=models.IntegerField(default=0),
        ),
    ]
