# Generated by Django 5.2.7 on 2025-10-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DispozenApp', '0012_eventmodel_vote_maybe_eventmodel_vote_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='conformation',
            field=models.BooleanField(default=False),
        ),
    ]
