# Generated by Django 5.2.7 on 2025-10-23 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DispozenApp', '0013_eventmodel_conformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispozenuser',
            name='partner_rating',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.CreateModel(
            name='OrganizerSendRequestToPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DispozenApp.eventmodel')),
                ('organizer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_requests', to=settings.AUTH_USER_MODEL)),
                ('partner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerSuccessfulEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DispozenApp.eventmodel')),
                ('partner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
