# Generated by Django 5.2.7 on 2025-10-23 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DispozenApp', '0014_dispozenuser_partner_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizersendrequesttopartner',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DispozenApp.eventmodel'),
        ),
        migrations.AlterField(
            model_name='organizersendrequesttopartner',
            name='organizer_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
