# Generated by Django 5.2.7 on 2025-10-23 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DispozenApp', '0015_alter_organizersendrequesttopartner_event_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizersendrequesttopartner',
            name='organizer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
