# Generated by Django 5.2.7 on 2025-10-23 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DispozenApp', '0016_alter_organizersendrequesttopartner_organizer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnersuccessfulevent',
            name='partner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='successful_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
