# Generated by Django 5.2.7 on 2025-10-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DispozenApp', '0017_alter_partnersuccessfulevent_partner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispozenuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
