# Generated by Django 5.2.7 on 2025-10-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DispozenApp', '0018_dispozenuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispozenuser',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
