# Generated by Django 5.2.7 on 2025-10-25 20:28

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DispozenApp', '0019_dispozenuser_location'),
    ]

    operations = [
        migrations.AddField(
    model_name='dispozenuser',
    name='name',
    field=models.CharField(max_length=100, blank=True, null=True),  # No unique=True
),
        migrations.AlterField(
            model_name='dispozenuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
