# Generated by Django 5.2.7 on 2025-10-26 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DispozenApp', '0020_dispozenuser_name_alter_dispozenuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispozenuser',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
