# Generated by Django 5.2.7 on 2025-10-26 02:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DispozenApp', '0021_alter_dispozenuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispozenuser',
            name='username',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
