# Generated by Django 5.2.7 on 2025-10-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DispozenApp', '0023_paymentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='status',
            field=models.BooleanField(blank=True, max_length=50, null=True),
        ),
    ]
