# Generated by Django 5.2.7 on 2025-10-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DispozenApp', '0024_alter_paymentmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='status',
            field=models.BooleanField(blank=True, default=False, max_length=50, null=True),
        ),
    ]
