# Generated by Django 5.2.7 on 2025-10-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DispozenApp', '0025_alter_paymentmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='confirm_schedule',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
