# Generated by Django 5.2.7 on 2025-10-26 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DispozenApp', '0026_eventmodel_confirm_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitedGuests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100)),
                ('guest_email', models.EmailField(max_length=100)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DispozenApp.eventmodel')),
            ],
        ),
    ]
