# Generated by Django 5.2.7 on 2025-10-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DispozenApp', '0027_invitedguests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitedguests',
            name='guest_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
