# Generated by Django 5.2.7 on 2025-10-26 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DispozenApp', '0028_alter_invitedguests_guest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='partner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
