# Generated by Django 5.2.7 on 2025-10-26 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DispozenApp', '0029_eventmodel_partner_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodel',
            name='schedule1_phase',
        ),
        migrations.RemoveField(
            model_name='eventmodel',
            name='schedule2_phase',
        ),
    ]
