# Generated by Django 5.2.7 on 2025-10-26 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DispozenApp', '0030_remove_eventmodel_schedule1_phase_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventmodel',
            old_name='partner_id',
            new_name='partner_name',
        ),
    ]
