# Generated by Django 5.2.7 on 2025-10-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DispozenApp', '0031_rename_partner_id_eventmodel_partner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='has_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
