# Generated by Django 5.2.7 on 2025-10-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DispozenApp', '0032_eventmodel_has_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='schedule1_going',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='schedule1_maybe',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='schedule1_not_going',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='schedule2_going',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='schedule2_maybe',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='schedule2_not_going',
            field=models.IntegerField(default=0),
        ),
    ]
