# Generated by Django 5.2.7 on 2025-10-26 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DispozenApp', '0033_eventmodel_schedule1_going_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventmodel',
            old_name='vote_maybe',
            new_name='going',
        ),
        migrations.RenameField(
            model_name='eventmodel',
            old_name='vote_no',
            new_name='maybe',
        ),
        migrations.RenameField(
            model_name='eventmodel',
            old_name='vote_yes',
            new_name='not_goint',
        ),
    ]
