# Generated by Django 5.2.7 on 2025-10-26 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DispozenApp', '0034_rename_vote_maybe_eventmodel_going_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventmodel',
            old_name='not_goint',
            new_name='not_going',
        ),
    ]
