# Generated by Django 5.2.7 on 2025-10-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DispozenApp', '0035_rename_not_goint_eventmodel_not_going'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='schedule_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='schedule_date_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
