# Generated by Django 5.2.7 on 2025-10-27 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DispozenApp', '0036_eventmodel_schedule_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispozenuser',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispozenuser',
            name='portfolio_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispozenuser',
            name='service_types',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
