# Generated by Django 5.2.7 on 2025-10-29 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DispozenApp', '0038_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='organizer_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
