# Generated by Django 5.2.7 on 2025-11-05 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DispozenApp', '0039_alter_eventmodel_organizer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DispozenApp.eventmodel')),
            ],
        ),
    ]
