# Generated by Django 5.2.7 on 2025-11-15 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DispozenApp', '0041_selectedplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedplace',
            name='organizer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_places', to=settings.AUTH_USER_MODEL),
        ),
    ]
