# Generated by Django 5.2.7 on 2025-11-15 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DispozenApp', '0042_alter_selectedplace_organizer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selectedplace',
            old_name='organizer_id',
            new_name='organizer',
        ),
    ]
