# Generated by Django 5.2.7 on 2025-11-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DispozenApp', '0044_alter_paymentmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='manychat_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selectedplace',
            name='manychat_location',
            field=models.BooleanField(default=False),
        ),
    ]
