# Generated by Django 5.2.7 on 2025-11-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DispozenApp', '0045_paymentmodel_manychat_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedplace',
            name='many_chat_location_request',
            field=models.BooleanField(default=False),
        ),
    ]
