# Generated by Django 5.2.7 on 2025-11-20 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DispozenApp', '0046_selectedplace_many_chat_location_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedplace',
            name='many_chat_location_request',
        ),
        migrations.AlterField(
            model_name='selectedplace',
            name='manychat_location',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
