# Generated by Django 5.2.7 on 2025-11-24 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DispozenApp', '0047_remove_selectedplace_many_chat_location_request_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='organizer',
            new_name='reciever_id',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='partner',
            new_name='sender_id',
        ),
    ]
