# Generated by Django 5.2.7 on 2025-11-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DispozenApp', '0048_rename_organizer_notification_reciever_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizersendrequesttopartner',
            name='partner_statues',
            field=models.BooleanField(default=False),
        ),
    ]
